/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as MeetingCodeRouteImport } from './routes/meeting.$code'
import { Route as ApiPublicLivekitWebhookRouteImport } from './routes/api/public/livekit-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingCodeRoute = MeetingCodeRouteImport.update({
  id: '/meeting/$code',
  path: '/meeting/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLivekitWebhookRoute = ApiPublicLivekitWebhookRouteImport.update({
  id: '/api/public/livekit-webhook',
  path: '/api/public/livekit-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/meeting/$code': typeof MeetingCodeRoute
  '/api/public/livekit-webhook': typeof ApiPublicLivekitWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/meeting/$code': typeof MeetingCodeRoute
  '/api/public/livekit-webhook': typeof ApiPublicLivekitWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/meeting/$code': typeof MeetingCodeRoute
  '/api/public/livekit-webhook': typeof ApiPublicLivekitWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/meeting/$code'
    | '/api/public/livekit-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/meeting/$code'
    | '/api/public/livekit-webhook'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/meeting/$code'
    | '/api/public/livekit-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  MeetingCodeRoute: typeof MeetingCodeRoute
  ApiPublicLivekitWebhookRoute: typeof ApiPublicLivekitWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meeting/$code': {
      id: '/meeting/$code'
      path: '/meeting/$code'
      fullPath: '/meeting/$code'
      preLoaderRoute: typeof MeetingCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/livekit-webhook': {
      id: '/api/public/livekit-webhook'
      path: '/api/public/livekit-webhook'
      fullPath: '/api/public/livekit-webhook'
      preLoaderRoute: typeof ApiPublicLivekitWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  MeetingCodeRoute: MeetingCodeRoute,
  ApiPublicLivekitWebhookRoute: ApiPublicLivekitWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
